practice1/practice1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("users/", include('users.urls')),
    path('admin/', admin.site.urls),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", include("allauth.urls")), #most important
]

practice1/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.custom_login, name="login"),
    path("logout/", views.custom_logout, name="logout"),
    path("profile/<username>/", views.profile, name="profile"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
]

practice1/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import os


class CustomUser(AbstractUser):
    def image_upload_to(self, instance=None):
        if instance:
            return os.path.join("users", self.username, instance)
        return None

    STATUS = (
        ('regular', 'regular'),
        ('subscriber', 'subscriber'),
        ('moderator', 'moderator'),
    )

    email = models.EmailField(unique=True)
    status = models.CharField(max_length=100, choices=STATUS, default='regular')
    description = models.TextField("Description", max_length=600, default='', blank=True)
    image = models.ImageField(default='default/user.jpg', upload_to=image_upload_to)

    def __str__(self):
        return self.username

practice1/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(help_text='A valid email address, please.',  required=True)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        return user

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class':'form-control', 'placeholder':'Username or Email'}),
        label="Username or Email*")

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'image', 'description']

practice1/users/views.py
from typing import Protocol
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage

from .forms import UserRegistrationForm, UserLoginForm, UserUpdateForm
from .decorators import user_not_authenticated
from .tokens import account_activation_token

def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, "Thank you for your email confirmation. Now you can login your account.")
        return redirect('login')
    else:
        messages.error(request, "Activation link is invalid!")

    return redirect('/')

def activateEmail(request, user, to_email):
    mail_subject = "Activate your user account."
    message = render_to_string("template_activate_account.html", {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'Dear <b>{user}</b>, please go to you email <b>{to_email}</b> inbox and click on \
                    received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.')
    else:
        messages.error(request, f'Problem sending email to {to_email}, check if you typed it correctly.')


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active=False
            user.save()
            activateEmail(request, user, form.cleaned_data['email'])
            return redirect('/')

        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    else:
        form = UserRegistrationForm()

    return render(
        request=request,
        template_name="users/register.html",
        context={"form": form}
    )

@login_required
def custom_logout(request):
    logout(request)
    messages.info(request, "Logged out successfylly")
    return redirect("homepage")


def custom_login(request):
    if request.method == "POST":
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )

            if user is not None:
                login(request, user)
                messages.success(request, f"Hello <b>{user.username}</b>! You have been logged in")
                return redirect('/')

    form = UserLoginForm()

    return render(
        request=request,
        template_name="users/login.html",
        context={"form": form}
    )

def profile(request, username):
    if request.method == "POST":
        user = request.user
        form = UserUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            user_form = form.save()
            messages.success(request, f'{user_form.username}, Your profile has been updated!')
            return redirect("profile", user_form.username)

        for error in list(form.errors.values()):
            messages.error(request, error)

    user = get_user_model().objects.filter(username=username).first()
    if user:
        form = UserUpdateForm(instance=user)
        form.fields['description'].widget.attrs = {'rows': 1}
        return render(
            request=request,
            template_name="users/profile.html",
            context={"form": form}
        )
    return redirect('/')

practice1/templates/home.html
<!DOCTYPE html>
<!-- Coding By CodingNepal - www.codingnepalweb.com -->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Responsive Website Homepage HTML and CSS | Alma Website</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <header class="header">
      <nav class="navbar">
        <h2 class="logo"><a href="#">Alma Website</a></h2>
        <input type="checkbox" id="menu-toggle" />
        <label for="menu-toggle" id="hamburger-btn">
          <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
            <path d="M3 12h18M3 6h18M3 18h18" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
          </svg>
        </label>
        <ul class="links">
          <li><a href="#">Home</a></li>
          <li><a href="#">About Us</a></li>
          <li><a href="#">Services</a></li>
          <li><a href="#">Portfolio</a></li>
          <li><a href="#">Contact Us</a></li>
        </ul>
        <div class="buttons">
          <a href="users/login" class="signin">Sign In</a>
          <a href="users/register" class="signup">Sign Up</a>
        </div>
      </nav>
    </header>
    <section class="hero-section">
      <div class="hero">
        <h2>Web App Development</h2>
        <p>
          Join us in the exciting world of programming and turn your ideas into
          reality. Unlock the world of endless possibilities - learn to code and
          shape the digital future with us.
        </p>
        <div class="buttons">
          <a href="#" class="join">Join Now</a>
          <a href="#" class="learn">Learn More</a>
        </div>
      </div>
      <div class="img">
        <img src="https://www.codingnepalweb.com/demos/create-responsive-website-html-css/hero-bg.png" alt="hero image" />
      </div>
    </section>
  </body>
</html>

<style>
    /* Importing Google font - Open Sans */
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap");
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: "Open Sans", sans-serif;
}
body {
  height: 100vh;
  width: 100%;
  background: linear-gradient(to bottom, #175d69 23%, #330c43 95%);
}
.header {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
}
.navbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px 15px;
}
.navbar .logo a {
  font-size: 1.8rem;
  text-decoration: none;
  color: #fff;
}
.navbar .links {
  display: flex;
  align-items: center;
  list-style: none;
  gap: 35px;
}
.navbar .links a {
  font-weight: 500;
  text-decoration: none;
  color: #fff;
  padding: 10px 0;
  transition: 0.2s ease;
}
.navbar .links a:hover {
  color: #47b2e4;
}
.navbar .buttons a {
  text-decoration: none;
  color: #fff;
  font-size: 1rem;
  padding: 15px 0;
  transition: 0.2s ease;
}
.navbar .buttons a:not(:last-child) {
  margin-right: 30px;
}
.navbar .buttons .signin:hover {
  color: #47b2e4;
}
.navbar .buttons .signup {
  border: 1px solid #fff;
  padding: 10px 20px;
  border-radius: 0.375rem;
  text-align: center;
  transition: 0.2s ease;
}
.navbar .buttons .signup:hover {
  background-color: #47b2e4;
  color: #fff;
}
.hero-section {
  display: flex;
  justify-content: space-evenly;
  align-items: center;
  height: 95vh;
  padding: 0 15px;
  max-width: 1200px;
  margin: 0 auto;
}
.hero-section .hero {
  max-width: 50%;
  color: #fff;
}
.hero h2 {
  font-size: 2.5rem;
  margin-bottom: 20px;
}
.hero p {
  font-size: 1.2rem;
  margin-bottom: 20px;
  color: #c9c7c7;
}
.hero-section .img img {
  width: 517px;
}
.hero-section .buttons {
  margin-top: 40px;
}
.hero-section .buttons a {
  text-decoration: none;
  color: #fff;
  padding: 12px 24px;
  border-radius: 0.375rem;
  font-weight: 600;
  transition: 0.2s ease;
  display: inline-block;
}
.hero-section .buttons a:not(:last-child) {
  margin-right: 15px;
}
.buttons .join {
  background-color: #47b2e4;
}
.hero-section .buttons .learn {
  border: 1px solid #fff;
  border-radius: 0.375rem;
}
.hero-section .buttons a:hover {
  background-color: #47b2e4;
}
/* Hamburger menu styles */
#menu-toggle {
  display: none;
}
#hamburger-btn {
  font-size: 1.8rem;
  color: #fff;
  cursor: pointer;
  display: none;
  order: 1;
}
@media screen and (max-width: 1023px) {
  .navbar .logo a {
    font-size: 1.5rem;
  }
  .links {
    position: fixed;
    left: -100%;
    top: 75px;
    width: 100%;
    height: 100vh;
    padding-top: 50px;
    background: #175d69;
    flex-direction: column;
    transition: 0.3s ease;
  }
  .navbar #menu-toggle:checked ~ .links {
    left: 0;
  }
  .navbar #hamburger-btn {
    display: block;
  }
  .header .buttons {
    display: none;
  }
  .hero-section .hero {
    max-width: 100%;
    text-align: center;
  }
  .hero-section img {
    display: none;
  }
}
</style>

practice1/users/templates/template_activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

{{ protocol }}://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

practice1/users/templates/users/login.html
{% load crispy_forms_tags %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log In</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(45deg, #4e79a7, #48c6ef);
            font-family: 'Roboto', sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            color: #fff;
        }
        .login-container {
            background-color: rgba(255, 255, 255, 0.9);
            padding: 40px;
            border-radius: 15px;
            box-shadow: 0px 15px 30px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 400px;
        }
        .login-container h2 {
            text-align: center;
            margin-bottom: 30px;
            color: #007bff;
            font-size: 28px;
            font-weight: 500;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-control {
            width: 100%;
            padding: 15px;
            font-size: 16px;
            border-radius: 10px;
            border: 1px solid #ddd;
            background-color: #f7f7f7;
            color: #333;
            transition: all 0.3s ease-in-out;
        }
        .form-control:focus {
            border-color: #007bff;
            background-color: #fff;
        }
        .btn {
            width: 100%;
            padding: 12px;
            font-size: 18px;
            border-radius: 10px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }
        .google-btn {
            background: linear-gradient(45deg, #4285F4, #34A853, #FBBC05, #EA4335);
            background-size: 300%;
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 12px;
            border-radius: 15px;
            text-decoration: none;
            font-size: 18px;
            font-weight: bold;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
            transition: all 0.4s ease-in-out;
        }
        .google-btn:hover {
            background-position: right;
            transform: scale(1.05);
            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.3);
        }
        .google-icon {
            margin-right: 10px;
            width: 24px;
            height: 24px;
        }
        .footer-links {
            text-align: center;
            margin-top: 20px;
        }
        .footer-links a {
            color: black;
            text-decoration: none;
            font-size: 14px;
            font-weight: bold;
        }
        .footer-links a:hover {
            text-decoration: underline;
        }
        .footer-links .text-muted {
            color: black !important;
        }
    </style>
</head>
<body>

<div class="login-container">
    <h2>Log In</h2>
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username" required>
        </fieldset>
        <fieldset class="form-group">
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" required>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
        <div class="form-group">
            <a href="{% provider_login_url 'google' %}?next=/" class="google-btn">
                <img src="https://img.icons8.com/ios-filled/50/ffffff/google-logo.png" alt="Google" class="google-icon"/>
                Sign in with Google
            </a>
        </div>
    </form>
    <div class="footer-links">
        <small class="text-muted">
            Need An Account? <a href="{% url 'register' %}">Sign Up Now</a>
        </small><br>
        <small class="text-muted">
            <a href="/">Forgot password?</a>
        </small>
    </div>
</div>

</body>
</html>

practice1/users/templates/users/logout.html
<h2>You have been logged out</h2>
    <div class="border-top pt-3"  style="min-height:65vh;">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>

practice1/users/templates/users/profile.html
{% load crispy_forms_tags %}
<div class="content-section col-lg-12 col-md-12 col-sm-12 tutorial-style" style="min-height:65vh;">
    <legend class="border-bottom mb-4">Profile Information:</legend>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="media">
            {% if user.username == form.instance.username %}
                <input id="id_image" type="file" name="image" hidden/>
                    <label for="id_image">
                        <img class="rounded-circle account-img profile-image"
                            style="cursor: pointer"
                            src="{{ form.instance.image.url }}"
                            title="Upload new image">
                    </label>
            {% else %}
                <img class="rounded-circle account-img profile-image", src="{{ form.instance.image.url }}">
            {% endif %}
            <div class="media-body">
                <h2 class="account-heading">{{ form.instance.username }}
                    <small class="text-muted">({{ form.instance.status }})</small>
                </h2>
                <p class="text-secondary">{{ form.instance.first_name }} {{ form.instance.last_name }}</p>
                <p class="text-secondary">{{ form.instance.email }}</p>
                <p class="text-secondary">{{ form.instance.description }}</p>
            </div>
        </div>

        {% if user.username == form.instance.username %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edit Profile Information</legend>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                </div>
                {{ form.email|as_crispy_field }}
                {{ form.description|as_crispy_field }}

                <a href="/">Change password?</a>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        {% endif %}
    </form>
</div>

practice1/users/templates/users/register.html
{% load crispy_forms_tags %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
    <!-- Font Awesome for Google Icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            background: linear-gradient(45deg, #6cace4, #b2e1f5);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .content-section {
            max-width: 500px;
            width: 100%;
            padding: 40px;
            background-color: white;
            border-radius: 10px;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
            transition: all 0.3s ease-in-out;
        }
        .content-section:hover {
            transform: scale(1.05);
        }
        .form-group legend {
            font-size: 1.8rem;
            color: #007bff;
            font-weight: 600;
            text-align: center;
        }
        .form-group label {
            font-weight: 500;
        }
        .form-control {
            border-radius: 5px;
            border: 1px solid #ddd;
            transition: border-color 0.3s ease;
        }
        .form-control:focus {
            border-color: #007bff;
            box-shadow: 0 0 0 0.2rem rgba(38, 143, 255, 0.5);
        }
        .btn-outline-info {
            background-color: #007bff;
            color: white;
            border-color: #007bff;
            transition: background-color 0.3s, color 0.3s;
            padding: 12px;
            font-size: 1.1rem;
            width: 100%;
            border-radius: 5px;
        }
        .btn-outline-info:hover {
            background-color: #0056b3;
            color: white;
        }
        .text-muted {
            font-size: 0.9rem;
            color: #555;
        }
        .text-muted a {
            color: #007bff;
        }
        .text-muted a:hover {
            text-decoration: underline;
        }
        .border-top {
            margin-top: 30px;
            border-top: 1px solid #e0e0e0;
        }
        .form-group input {
            margin-bottom: 15px;
        }
        .form-group .form-control {
            font-size: 1.1rem;
            padding: 12px;
        }
    </style>
</head>
<body>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend>Join Today</legend>
                {{ form|crispy }}
            </fieldset>

            <p class="text-muted text-center">By registering, you accept the Terms of Service and Privacy Notice</p>

            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>

        <!-- Google Login Button -->
        <div class="form-group">
        <a href="{% provider_login_url 'google' %}?next=/" class="btn btn-danger btn-block">
            <i class="fab fa-google"></i> Sign Up with Google
        </a>

        </div>

        <div class="border-top pt-3">
            <small class="text-muted text-center">
                Already Have An Account? <a href="/login">Sign In</a>
            </small>
        </div>
    </div>

    <!-- Bootstrap JS و وابستگی‌ها -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>